### PR TITLE
Updated for CocoaPods support

### PR DESCRIPTION
**Pull request by hemangshah**
Fixed error: Cannot inherit from non-open class (Class)" outside of its
defining module

### CODE REVIEW

**Review by hemangshah — COMMENTED** [review]
Please merge this PR. Currently, we are not able to access SplashViewController.

**Comment by hemangshah** [comment]
screen shot 2017-10-16 at 12 40 45 pm

**Comment by hemangshah** [comment]
Can you please make a new release on CocoaPods? @okaris

**Comment by okaris** [comment]
Released

**Comment by hemangshah** [comment]
Thank you @okaris

**Pull request merged**
