### PR TITLE
Swift 4 support

### PR DESCRIPTION
**Pull request by hemangshah**

### CODE REVIEW

**Comment by okaris** [comment]
@hemangshah will this work with Swift 3 projects? If not this should be a seperate branch.

**Comment by hemangshah** [comment]
@okaris, sorry, it won't works with Swift 3 projects. I am not sure, how to move this PR to a new branch? Please guide me on that.

**Comment by okaris** [comment]
Thanks for the PR. Merged it into the new swift4 branch and updated readme on how to use that branch as a pod.

**Comment by hemangshah** [comment]
Thanks @okaris 👍

**Pull request merged**
